### ISSUE TITLE
"ImportError: No module named topic_monitor"

### ISSUE THREAD

**Issue by 130s** [130s/monitoring_tools#1]
# Issue

Using a tentative [feature-rospy-binding_catkin](https://github.com/130s/monitoring_tools/tree/feature-rospy-binding_catkin) branch,

```
# rosrun topic_monitor_ros1 topic_monitor 
Traceback (most recent call last):
  File "/cws/install/lib/topic_monitor_ros1/topic_monitor", line 3, in <module>
    from topic_monitor_ros1.topic_monitor import TopicMonitorRos1
  File "/cws/install/lib/python2.7/dist-packages/topic_monitor_ros1/topic_monitor.py", line 20, in <module>
    from topic_monitor.topic_monitor import AbstDataReceivingThread, TopicMonitor
ImportError: No module named topic_monitor
```

Confirmed on `ipython`:
```
In [12]: from topic_monitor_ros1.topic_monitor import TopicMonitorROS1
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-12-b53ed353f636> in <module>()
----> 1 from topic_monitor_ros1.topic_monitor import TopicMonitorROS1

/cws/install/lib/python2.7/dist-packages/topic_monitor_ros1/topic_monitor.py in <module>()
     18 from threading import Lock, Thread
     19 
---> 20 from topic_monitor.topic_monitor import AbstDataReceivingThread, TopicMonitor
     21 
     22 

ImportError: No module named topic_monitor
```

# Counter

The same `from` line doesn't yield the error when called individually on `ipython`.
```
In [13]: from topic_monitor.topic_monitor import AbstDataReceivingThread, TopicMonitor
    ...: 

In [14]: 
```

**Comment by 130s** [comment]
```
root@130s-p50:/cws# env|grep -i py
ROS_PYTHON_VERSION=2
PYTHONPATH=/cws/install/lib/python2.7/dist-packages:/opt/ros/melodic/lib/python2.7/dist-packages

root@130s-p50:/cws# env|grep -i ros
LD_LIBRARY_PATH=/cws/install/lib:/opt/ros/melodic/lib
ROS_ETC_DIR=/opt/ros/melodic/etc/ros
CMAKE_PREFIX_PATH=/cws/install:/opt/ros/melodic
ROS_ROOT=/opt/ros/melodic/share/ros
ROS_MASTER_URI=http://localhost:11311
ROS_VERSION=1
ROS_PYTHON_VERSION=2
PYTHONPATH=/cws/install/lib/python2.7/dist-packages:/opt/ros/melodic/lib/python2.7/dist-packages
ROS_PACKAGE_PATH=/cws/install/share:/opt/ros/melodic/share
ROSLISP_PACKAGE_DIRECTORIES=
PATH=/opt/ros/melodic/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PKG_CONFIG_PATH=/cws/install/lib/pkgconfig:/opt/ros/melodic/lib/pkgconfig
ROS_DISTRO=melodic
```
